# Auth
## signup - create
###
POST http://localhost:3000/signup
content-type: application/json

{
    "id": "+799923423494",
    "password": "1213"
}

###
POST http://localhost:3000/signup
content-type: application/json

{
    "id": "dfgd1f@dfd.rt",
    "password": "1213"
}

## signin
###
POST http://localhost:3000/signin
content-type: application/json

{
    "id": "+79992342343",
    "password": "1213"
}
